export const  ServerVariables = {
    // landing
    Landing:'/',
    about:'/about',

    //userRoutes

    Login:'/login',
    Register: "/register",
    verifyOtp:'/verifyOtp',
    userHome:"/userHome",
    explore:'/explore',
    verifyEmail:'/verifyEmail',
    forgetOtp:'/forgetOtp',
    changePassword:'/changePassword',
    userProfile:'/userProfile',
    editUserProfile:'/editUserProfile',
    addPost:'/addPost',
    showArtists:'/showArtists',
    chatWithArtist:'/chatWithArtist',
    userNotifications:'/userNotifications',
    viewArtistDetails:'/viewArtistDetails',
    userVideoCall:'/userVideoCall/:roomId/:artistId',

    //artistRoutes
    ArtistLogin:'/artistLogin',
    ArtistRegister:'/artistRegister',
    ArtistVerifyOtp:'/artistOtp',
    ArtistHome:'/artistHome',
    artistProfile:'/artistProfile',
    editArtistProfile:'/editArtistProfile',
    plansAvailable:'/plansAvailable',
    mySubscriptions:'/mySubscriptions',
    artistPosts:'/artistPosts',
    successPage:'/successPage',
    errorPage:'/errorPage',
    aboutPage:'/aboutPage',
    artistChatPage:'/artistChatPage',
    getPrevMessages: "/api/artist/getPrevMessages",
    artistNotifications:'/artistNotifications',
    artistVideoCall:'/artistVideoCall/:roomId/:userId',

    //Admin Routes
    AdminLogin:'/adminLogin',
    AdminDashboard:'/dashboard',
    Users:'/Users',
    Artists:'/artists',
    Categories:'/categories',
    AddCategory:'/addCategory',
    EditCategory:'/editCategory',
    ViewArtist:'/ViewArtist',
    Plans:'/plans',
    Editplan:'/editPlan',
    AddPlan:'/addPlan',
    banners:'/banners',
    addBanner:'/addBanner',
    editBanner:'/editBanner',
    subscriptionPlanHistory:'/subscriptionPlanHistory',
}